[package]
name = "vre-core"
version = "0.1.0"
edition = "2021"
description = "Vyauma Runtime Engine core"
license = "Apache-2.0"

[dependencies]
 
[dev-dependencies]
vre-vol = { path = "../vre-vol" }
